import { getProviderConnection } from '../_auth.js';

function fail(res, status, message) {
  res.status(status).json({ error: message });
}

function toGoogleDate(dateStr, timeStr) {
  return `${dateStr}T${timeStr}:00+09:00`;
}

export default async function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST,OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
  res.setHeader('Cache-Control', 'no-store');

  if (req.method === 'OPTIONS') {
    res.status(204).end();
    return;
  }

  if (req.method !== 'POST') {
    fail(res, 405, 'Method not allowed');
    return;
  }

  const google = await getProviderConnection(req, 'google');
  if (!google?.accessToken) {
    fail(res, 401, 'Google Calendar is not connected');
    return;
  }

  const body = typeof req.body === 'string' ? JSON.parse(req.body || '{}') : (req.body || {});
  if (!body.selectedSlot?.date || !body.selectedSlot?.time) {
    fail(res, 400, 'selectedSlot is required');
    return;
  }

  const durationMinutes = Number(body.duration || 20);
  const start = new Date(toGoogleDate(body.selectedSlot.date, body.selectedSlot.time));
  const end = new Date(start.getTime() + durationMinutes * 60000);
  const calendarId = process.env.GOOGLE_CALENDAR_ID || 'primary';

  const response = await fetch(`https://www.googleapis.com/calendar/v3/calendars/${encodeURIComponent(calendarId)}/events`, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${google.accessToken}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      summary: body.summary || 'Coffee chat',
      description: body.description || 'Generated by Linkflow',
      start: {
        dateTime: start.toISOString(),
        timeZone: 'Asia/Seoul',
      },
      end: {
        dateTime: end.toISOString(),
        timeZone: 'Asia/Seoul',
      },
      attendees: body.attendees || [],
    }),
  });

  const data = await response.json();
  res.status(response.ok ? 200 : response.status).json(data);
}
