import { addBooking, listBookings } from './_store.js';
import { getProviderConnection } from './_auth.js';

function sendJson(res, status, payload) {
  res.status(status).setHeader('Content-Type', 'application/json; charset=utf-8');
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Cache-Control', 'no-store');
  res.json(payload);
}

export default async function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET,POST,OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
  res.setHeader('Cache-Control', 'no-store');

  if (req.method === 'OPTIONS') {
    res.status(204).end();
    return;
  }

  if (req.method === 'GET') {
    sendJson(res, 200, { bookings: await listBookings() });
    return;
  }

  if (req.method === 'POST') {
    try {
      const body = typeof req.body === 'string' ? JSON.parse(req.body || '{}') : (req.body || {});
      let booking = await addBooking(body);

      const google = await getProviderConnection(req, 'google');
      if (google?.accessToken && body.selectedSlot?.date && body.selectedSlot?.time) {
        const durationMinutes = Number(body.duration || 20);
        const start = new Date(`${body.selectedSlot.date}T${body.selectedSlot.time}:00+09:00`);
        const end = new Date(start.getTime() + durationMinutes * 60000);
        const calendarId = process.env.GOOGLE_CALENDAR_ID || 'primary';

        const response = await fetch(`https://www.googleapis.com/calendar/v3/calendars/${encodeURIComponent(calendarId)}/events`, {
          method: 'POST',
          headers: {
            Authorization: `Bearer ${google.accessToken}`,
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({
            summary: body.meetingType || 'Coffee chat',
            description: body.guest?.message || 'Generated by Linkflow',
            start: { dateTime: start.toISOString(), timeZone: 'Asia/Seoul' },
            end: { dateTime: end.toISOString(), timeZone: 'Asia/Seoul' },
            attendees: body.guest?.email ? [{ email: body.guest.email }] : [],
          }),
        });

        if (response.ok) {
          const event = await response.json();
          booking = { ...booking, calendarEventId: event.id, calendarHtmlLink: event.htmlLink || '' };
        }
      }

      sendJson(res, 201, booking);
    } catch (error) {
      sendJson(res, 400, { error: error.message || 'Invalid booking payload' });
    }
    return;
  }

  sendJson(res, 405, { error: 'Method not allowed' });
}
